apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-hello-world
  namespace: f5-configmap-ns
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: f5-hello-world
    spec:
      containers:
      - name: f5-hello-world
        image: myf5/f5-hello-world
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  labels:
    location: f5
    f5-svc: f5helloworldservice
  name: f5-hello-word-service
  namespace: f5-configmap-ns
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: f5-hello-world